server:
  port: 10001
spring:
  application:
    name: terragateway

  cloud:
    gateway:
      routes:
        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/api/**
        - id: productservice
          uri: lb://productservice
          predicates:
           - Path=/product/**
        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
           - Path=/api/**
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10002/eureka/

  instance:
    hostname: localhost
    